# Generated by Django 4.1.2 on 2022-10-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128, unique=True)),
                ('lastname', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
