# Generated by Django 4.1.2 on 2022-10-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverlicense', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('animalname', models.CharField(max_length=128, unique=True)),
                ('animalid', models.CharField(max_length=128, unique=True)),
                ('otherpets', models.CharField(max_length=256)),
                ('homecheck', models.CharField(max_length=128)),
                ('checkcalls', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.user')),
            ],
        ),
    ]
